"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.canciones = void 0;
exports.canciones = [
    {
        titulo: "Punching Bag",
        duracionSegundos: 189,
        bpm: 100,
        genero: "indie pop",
        estadoDeAnimo: "melancolico",
        energia: 6,
        rareza: "single",
    },
    {
        titulo: "23",
        duracionSegundos: 174,
        bpm: 140,
        genero: "indie pop",
        estadoDeAnimo: "nostalgico",
        energia: 8,
        rareza: "single",
    },
    {
        titulo: "Headache",
        duracionSegundos: 165,
        bpm: 150,
        genero: "alt-rock",
        estadoDeAnimo: "euforico",
        energia: 9,
        rareza: "single",
    },
    {
        titulo: "Wisdom Tooth",
        duracionSegundos: 180,
        bpm: 132,
        genero: "alt-rock",
        estadoDeAnimo: "sereno",
        energia: 7,
        rareza: "single",
    },
    {
        titulo: "Japan",
        duracionSegundos: 210,
        bpm: 78,
        genero: "bedroom pop",
        estadoDeAnimo: "melancolico",
        energia: 3,
        rareza: "b-side",
    },
    {
        titulo: "The Hardest Working Man Alive",
        duracionSegundos: 168,
        bpm: 128,
        genero: "indie pop",
        estadoDeAnimo: "melancolico",
        energia: 7,
        rareza: "b-side",
    },
    {
        titulo: "Funeral",
        duracionSegundos: 200,
        bpm: 118,
        genero: "indie rock",
        estadoDeAnimo: "melancolico",
        energia: 6,
        rareza: "single",
    },
    {
        titulo: "Best Friend",
        duracionSegundos: 172,
        bpm: 124,
        genero: "synth pop",
        estadoDeAnimo: "nostalgico",
        energia: 7,
        rareza: "single",
    },
    {
        titulo: "Loser at Best",
        duracionSegundos: 188,
        bpm: 145,
        genero: "indie rock",
        estadoDeAnimo: "euforico",
        energia: 8,
        rareza: "single",
    },
    {
        titulo: "Disappear",
        duracionSegundos: 220,
        bpm: 96,
        genero: "alt-pop",
        estadoDeAnimo: "sereno",
        energia: 4,
        rareza: "b-side",
    },
];
//# sourceMappingURL=canciones.js.map